# -*- coding: utf-8 -*-
"""抓台灣天氣.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wWCCsoE-CuQQGm_C-i48Y5wbWBKknn1m

#抓中央氣象局的天氣API
"""

import requests

# 定義 API URL
url = 'https://opendata.cwa.gov.tw/api/v1/rest/datastore/O-A0001-001?Authorization=CWA-EE6B8274-64E0-4976-9922-F433E68CB68E&format=JSON'

# 發送請求並取得 JSON 資料
try:
    response = requests.get(url)
    response.raise_for_status()  # 確保請求成功
    data = response.json()
except requests.exceptions.RequestException as e:
    print(f"無法取得資料: {e}")
    exit()

# 解析氣象資料
stations = data.get("records", {}).get("Station", [])
if not stations:
    print("無法找到測站資料")
    exit()

# 遍歷測站資料
for station in stations:
    # 提取測站基本資訊
    station_name = station.get("StationName", "未知測站")  # 測站名稱
    geo_info = station.get("GeoInfo", {})
    county = geo_info.get("CountyName", "未知縣市")  # 縣市
    town = geo_info.get("TownName", "未知鄉鎮")  # 鄉鎮

    # 提取氣象資料
    weather_elements = station.get("WeatherElement", {})
    weather = weather_elements.get("Weather", "無資料")  # 抓天氣狀態

    # 印出結果
    print(f"{county} {town} 的 {station_name} 天氣是 {weather}")

"""---

#用pandas 篩選晴天的地方
"""

import requests
import pandas as pd


# 將資料轉換為 Pandas DataFrame
data_list = []
for station in stations:
    station_name = station.get("StationName", "未知測站")
    county = station.get("GeoInfo", {}).get("CountyName", "未知縣市")
    town = station.get("GeoInfo", {}).get("TownName", "未知鄉鎮")
    weather = station.get("WeatherElement", {}).get("Weather", "無資料")

    # 添加資料到列表
    data_list.append({"測站名稱": station_name, "縣市": county, "鄉鎮": town, "天氣": weather})

# 創建 DataFrame
df = pd.DataFrame(data_list)

# 篩選出天氣為「晴」的地點
sunny_places = df[df["天氣"] == "晴"]

# 印結果
print("天氣為晴的地點：")
print("-"*50)
print(sunny_places)